# Generated by Django 3.1 on 2020-09-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='id',
        ),
        migrations.AddField(
            model_name='shift',
            name='identity',
            field=models.AutoField(default=1111, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='tip'),
            preserve_default=False,
        ),
    ]
