# Generated by Django 3.1 on 2020-09-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20200916_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='tip',
            field=models.DecimalField(decimal_places=2, max_digits=2, verbose_name='tip'),
        ),
    ]
